### ISSUE TITLE
rspec - "calls on #load_library and gives it the argument of the file path" problem

### ISSUE THREAD

**Issue by garettarrowood** [learn-co-curriculum/emoticon-translator#2]
Perhaps there was another way to write my code to pass this test, but it seems the test suite had a problem with me calling the #load_library twice in my method.  Below is the code I used.  I couldn't get this particular test to pass (only one in lab), so I commented it out.

def get_japanese_emoticon(file_path, emoticon)
	if load_library(file_path)["get_emoticon"][emoticon]
		load_library(file_path)["get_emoticon"][emoticon]
	else
		"Sorry, that emoticon was not found"
	end
end

**Comment by BenjaGross** [comment]
@garettarrowood the code you have above loads the library twice, and the test requires that #load_library is only called once because we don't want to open the file multiple times in the same method, the code works fine if `load_library(file_path)` is saved as a variable. The suggested solution is 
```
def get_japanese_emoticon(file_path, emoticon)
  library = load_library(file_path)
  result = library["get_emoticon"][emoticon]
  if result
    result
  else
    "Sorry, that emoticon was not found"
  end
end
```

Do you think that we should add to the readme that load_library should only be called once in each method?

**Comment by garettarrowood** [comment]
That does make sense.  Thank you for the explanation!
