### ISSUE TITLE
Wrong phrasing in test suite

### ISSUE THREAD

**Issue by jeffslutzky** [learn-co-curriculum/emoticon-translator#4]
Hi, I'm currently going through this exercise and noticed an error in the test suite. For the method get_english_meaning, the tests say:

"it "returns the Japanese equivalent of an English grinning" do

Shouldn't that be "returns the English meaning of a Japanese emoticon" rather than copying the language for the previous method's test? I was confused when I first looked at this.

**Comment by AnnJohn** [comment]
Hi @jeffslutzky, thanks for raising this issue. We're reviewing our curriculum in sequential order, so for now I'm going to put your issue on icebox and when we get to this portion of the curriculum, we'll "thaw" it out. 

Since it looks like though your question needs a more immediate response, please use the "Ask a Question" tool in Learn and one of our instructors will get back you much sooner than when the issue will be fixed. Thanks again.
